import{a as v,S as M,i as s}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const P="https://pixabay.com/api/",R="49365626-6bf9b0bb5948f971197bdaec6";async function p(e,t=1,n=15){return(await v.get(P,{params:{key:R,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}let u=null;function q(e){e.innerHTML=""}function y(e){return e.map(t=>`
            <a href="${t.largeImageURL}" class="gallery-item">
                <img 
                    src="${t.webformatURL}" 
                    alt="${t.tags}" 
                    loading="lazy"
                />
            </a>
            `).join("")}function L(e,t){e.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new M(".gallery a",{captionsData:"alt",captionDelay:250})}const E=document.querySelector(".search-form"),l=document.querySelector(".gallery"),a=document.querySelector(".load-more"),b=document.querySelector(".loader");let f="",c=1;const m=15;let g=0;a.classList.add("hidden");E.addEventListener("submit",I);async function I(e){e.preventDefault();const t=e.target.elements.searchQuery.value.trim();if(!t){s.warning({message:"Please enter a search query",position:"topRight"});return}f=t,c=1,g=0,q(l),h();try{S();const n=await p(f,c,m);if(g=n.totalHits,n.hits.length===0){s.warning({message:"No images found",position:"topRight"});return}const i=y(n.hits);L(l,i),w()}catch{s.warning({message:"Something went wrong. Please try again",position:"topRight"})}finally{h()}}a.addEventListener("click",O);async function O(){c+=1;try{S(),a.disabled=!0;const e=await p(f,c,m),t=y(e.hits);L(l,t),x(),w()}catch{s.warning({message:"Error loading more images",position:"topRight"})}finally{h(),a.disabled=!1}}function w(){c*m>g?(H(),s.warning({message:"You've reached the end of the results",position:"topRight"})):B()}function S(){b.classList.remove("hidden")}function h(){b.classList.add("hidden")}function B(){a.classList.remove("hidden")}function H(){a.classList.add("hidden")}function x(){const{height:e}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
