import{a as q,i as s}from"./assets/vendor-LaWSutCc.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const E="https://pixabay.com/api/",P="49365626-6bf9b0bb5948f971197bdaec6",M=q.create({baseURL:E,params:{key:P,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function m(t,r=1,n=15){try{return(await M.get("",{params:{q:t,page:r,per_page:n}})).data}catch(a){throw console.error("Error fetching images:",a),a}}function h(t){return t.map(({webformatURL:r,largeImageURL:n,tags:a,likes:e,views:o,comments:i,downloads:v})=>`
                    <li class="gallery-item">
                        <a href="${n}" class="gallery-link">
                            <img src="${r}" alt="${a}" loading="lazy" class="gallery-image"/>
                        </a>

                        <div class="info">
                            <p><b>Likes</b> ${e}</p>
                            <p><b>Views</b> ${o}</p>
                            <p><b>Comments</b> ${i}</p>
                            <p><b>Downloads</b> ${v}</p>
                        </div>
                    </li>`).join("")}function y(t,r){t.insertAdjacentHTML("beforeend",r)}function R(t){t.innerHTML=""}const S=document.querySelector(".search-form"),l=document.querySelector(".gallery"),f=document.querySelector(".load-more"),b=document.querySelector(".loader");let d="",c=1;const g=15;let u=0;S.addEventListener("submit",O);async function O(t){t.preventDefault();const r=t.target.elements.query.value.trim();if(!r){s.warning({message:"Please enter a search query",position:"topRight"});return}d=r,c=1,u=0,R(l),p();try{w();const n=await m(d,c,g);if(u=n.totalHits,n.hits.length===0){s.warning({message:"No images found",position:"topRight"});return}const a=h(n.hits);y(l,a),L()}catch{s.warning({message:"Something went wrong. Please try again",position:"topRight"})}finally{p()}}f.addEventListener("click",$);async function $(){c+=1;try{const t=await m(d,c,g),r=h(t.hits);y(l,r),L();const{height:n}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}catch{s.warning({message:"Error loading more images",position:"topRight"})}finally{p()}}function L(){c*g>u?(A(),s.warning({message:"You've reached the end of the results",position:"topRight"})):I()}function w(){b.classList.remove("hidden")}function p(){b.classList.add("hidden")}function I(){f.classList.remove("hidden")}function A(){f.classList.add("hidden")}
//# sourceMappingURL=index.js.map
